name: Rust tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rust_tests:
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-rust
        with:
          cache-key: "tests"

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Cargo clippy
        run: ./scripts/lint.sh

      - name: Cargo test
        run: ./scripts/test.sh
